### ISSUE TITLE
Testes e análise estática (estão faltando)

### ISSUE THREAD

**Issue by kyriosdata** [rebeccamoraes/cs-2019-01#11]

**Comment by rebeccamoraes** [comment]
Todas os erros identificados pelo Eslint foram corrigidos no commit bfcf5d1c9b189467c9ecbd4e3f364b8b8df016b8, exceto os do tipo "função definida mas nunca usada".

**Comment by rebeccamoraes** [comment]
Análise estática da versão java seguindo o analisador pmd realizada no commit 9f78f0f681ec73eeb68c4eb68864c2a98978bcea.

**Comment by rebeccamoraes** [comment]
Testes em java com 100% de cobertura 32c5fdfd43a8c1e9bb0bfd0c89c84eb45497d46a

**Comment by rebeccamoraes** [comment]
Análise estática com checkstyle realizada no commit e8120cda88a43e9370bcb32bb354cfa6e6a64eae
Todos os erros foram corrigidos, com exceção de alguns magic numbers.

**Comment by kyriosdata** [comment]
Vou verificar.

**Comment by rebeccamoraes** [comment]
Testes das funções em javascript finalizados no commit 0bb49bc42a9a586406ae6147040ec0eed60d8e1a.
