### ISSUE TITLE
Atualize o seu .gitignore

### ISSUE THREAD

**Issue by kyriosdata** [rebeccamoraes/cs-2019-01#12]
- Não é preciso fornecer um caminho, conforme você fez, exceto se desejar apenas este caminho. 
- Acrescente a linha "bin/" (ignorar o que for gerado em diretórios bin, onde quer que apareçãm)
- Acrescentar "*.class", pois você provavelmente não terá interesse nestes arquivos. Talvez esta linha não seja necessária, basta que você coloque todo o código gerado em diretório bem definido, se o diretório é removido, então não existirá .class "perdido".

**Comment by rebeccamoraes** [comment]
Resolvido com o commit 29f4b6ebdfef283ffb6d7c86a4502bd19c05af09
