### ISSUE TITLE
Documentação incompleta

### ISSUE THREAD

**Issue by kyriosdata** [rebeccamoraes/cs-2019-01#6]
- Obviamente você sabe, há muitas funções que ainda não estão documentadas. Adicionalmente, por exemplo, para a função cpf2, a documentação "Cadastro de Pessoas Físicas (CPF)" não diz muito. Diria algo imediato assim: "Implementação alternativa de verificação de CPF". Estamos falando de JavaScript. 
- Na linha 527, a declaração correta não é "vetor", mas "Array.<number>". Sugiro verificar no portal do jsDoc.

**Comment by rebeccamoraes** [comment]
Na linha 527, a declaração correta não é "vetor", mas "Array.". Sugiro verificar no portal do jsDoc.
Corrigido no commit https://github.com/rebeccamoraes/cs-2019-01/commit/12b150a72967307d42785a90a374608acb9f7058

**Comment by rebeccamoraes** [comment]
Complementação da documentação realizada no commit https://github.com/rebeccamoraes/cs-2019-01/commit/181a7895402cfc454b6352d4a6bc82465aaa5572
