### ISSUE TITLE
Não use parâmetro como variável local

### ISSUE THREAD

**Issue by kyriosdata** [rebeccamoraes/cs-2019-01#9]
Observe que nas linhas 100 e 101, exercicios-iniciais.js, você faz o oposto. Idealmente você tem que definir uma variável para o ano e outra para o mês para acomodar este possível ajuste.

**Comment by rebeccamoraes** [comment]
Resolvido no commit c770a23790f5ca9fa2bcdcaf80b36589fcd1028f.
